import { hashSync } from "bcrypt-ts-edge";

const sampleData = {
  characters: [
    {
      name: "Hubert",
      slug: "hubert",
      campaign: "Electric Blueberries",
      image: "/images/characters/annie.jpg",
      player: "Annie",
      primaryRole: "Thief",
      secondaryRole: "",
      secondaryRole2: "",
    },
    {
      name: "Harold",
      slug: "harold",
      campaign: "Electric Blueberries",
      image: "/images/characters/katrin.jpg",
      player: "Katrin",
      primaryRole: "Muscle",
      secondaryRole: "",
      secondaryRole2: "",
    },
    {
      name: "???",
      slug: "???",
      campaign: "Electric Elderberries",
      image: "/images/characters/kat.jpg",
      player: "Kat",
      primaryRole: "Hacker",
      secondaryRole: "",
      secondaryRole2: "",
    },
    {
      name: "Mortimer",
      slug: "mortimer",
      campaign: "Electric Elderberries",
      image: "/images/characters/nadja.jpg",
      player: "Nadja",
      primaryRole: "Face",
      secondaryRole: "",
      secondaryRole2: "",
    },
    {
      name: "Hubert",
      slug: "hubert2",
      campaign: "Electric Blueberries",
      image: "/images/characters/annie.jpg",
      player: "Annie",
      primaryRole: "",
      secondaryRole: "",
      secondaryRole2: "",
    },
    {
      name: "Harold",
      slug: "harold2",
      campaign: "Electric Blueberries",
      image: "/images/characters/katrin.jpg",
      player: "Katrin",
      primaryRole: "",
      secondaryRole: "",
      secondaryRole2: "",
    },
    {
      name: "Mortimer",
      slug: "mortimer2",
      campaign: "Electric Elderberries",
      image: "/images/characters/nadja.jpg",
      player: "Nadja",
      primaryRole: "",
      secondaryRole: "",
      secondaryRole2: "",
    },
  ],
  users: [
    {
      name: "Nadja",
      email: "admin@admin.com",
      password: hashSync("123456", 10),
      role: "admin",
    },
    {
      name: "Eva",
      email: "user@admin.com",
      password: hashSync("123456", 10),
      role: "user",
    },
  ],
};

export default sampleData;
